<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src-dotnet\SecureMessaging.Contracts\SecureMessaging.Contracts.csproj" />
    <ProjectReference Include="..\..\src-dotnet\SecureMessaging.Client\SecureMessaging.Client.csproj" />
  </ItemGroup>
</Project>
